[build]
  base = "frontend"
  command = "pnpm build"
  publish = ".next"
  environment = { NODE_VERSION = "20.17.0" }

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/generateResume"
  to = "/.netlify/functions/api_generateResume"
  status = 200
  force = true

[[redirects]]
  from = "/api/serveTemp/:sessionId"
  to = "/.netlify/functions/api_serveTemp/:sessionId"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200